name: bocagoi
description: Bocagoi language learning mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  localstorage: ^3.0.0
  shared_preferences: '>=0.5.12+4 <2.0.0'
  cupertino_icons: ^1.0.0

  # Firebase: Updated 2020 November
  # Do not upgrade or use ^, they break backwards compat sometimes.

  firebase_core: 0.5.2+1 # if breaks, use ^0.4.4 (orig 0.5.2+1)
  cloud_firestore: 0.14.3+1 # if breaks, use 0.13.6 (orig 0.14.3+1)

  firebase_auth: 0.18.3+1
  google_sign_in: 4.5.6

  firebase_analytics: 6.2.0 # if breaks, use ^5.0.0 (orig 6.2.0)
  firebase_crashlytics: 0.2.3+1 # if breaks, ^use 0.1.0 (orig 0.2.3+1)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
